# Generated by Django 2.0.7 on 2021-06-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('rem', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bus_name',
            new_name='train_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='busid',
            new_name='trainid',
        ),
    ]
